In [1]:
import numpy as np
import os
from scipy.linalg import eigh, qr, null_space
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'DejaVu Sans'
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable
from scipy.sparse import eye, kron, identity, csr_matrix, csc_matrix, lil_matrix, dok_matrix, issparse, coo_matrix
from scipy.sparse.linalg import eigsh, eigs, lobpcg, LinearOperator, ArpackNoConvergence
from scipy.optimize import curve_fit
from qutip import Qobj, ptrace, entropy_vn, qeye, tensor
from tqdm import tqdm   
import time
from itertools import product
from functools import reduce
import torch
import torch.optim as optim
from torch.autograd import Variable
import sympy as sp
from collections import Counter

In [2]:
def pauli_x():
    """Pauli X matrix."""
    return np.array([[0, 1], [1, 0]])

def pauli_z():
    """Pauli Z matrix."""
    return np.array([[1, 0], [0, -1]])

def dodecahedral_bonds(): #20 vertices
    """
    Defines the connectivity of a true 20-vertex dodecahedral molecular structure.

    Returns:
        list of tuples: Each tuple (i, j) represents a bond between spin i and spin j.
    """
    bonds = [
    (0, 13), (0, 14), (0, 15),
    (1, 4), (1, 5), (1, 12),
    (2, 6), (2, 13), (2, 18),
    (3, 7), (3, 14), (3, 19),
    (4, 10), (4, 18),
    (5, 11), (5, 19),
    (6, 10), (6, 15),
    (7, 11), (7, 15),
    (8, 9), (8, 13), (8, 16),
    (9, 14), (9, 17),
    (10, 11),
    (12, 16), (12, 17),
    (16, 18),
    (17, 19)
]

    return bonds


def transverse_field_ising_dodecahedral(N, J, h):
    """
    Constructs the Hamiltonian for the transverse field Ising model on a dodecahedral molecular structure.

    Parameters:
        N (int): Number of spins (should match the dodecahedral molecule, typically N=12).
        J (float): Interaction strength.
        h (float): Transverse field strength.
    
    Returns:
        H (scipy.sparse.csr_matrix): The Hamiltonian matrix in sparse format.
    """
    if N != 20:
        raise ValueError("Dodecahedral molecules typically have N = 20 sites.")

    # Sparse identity matrix
    I = identity(2, format="csr")
    
    # Pauli matrices as sparse matrices
    X = csr_matrix(pauli_x())
    Z = csr_matrix(pauli_z())
    
    # Initialize the Hamiltonian
    H = csr_matrix((2**N, 2**N), dtype=np.float64)

    # Get dodecahedral bonds
    bonds = dodecahedral_bonds()

    # Interaction term: J * sigma_i^x * sigma_j^x for dodecahedral connectivity
    for i, j in bonds:
        term = 1
        for k in range(N):
            if k == i or k == j:
                term = kron(term, X, format="csr")
            else:
                term = kron(term, I, format="csr")
        H += J * term
    
    # Transverse field term: -h * sigma_i^z
    for i in range(N):
        term = 1
        for j in range(N):
            if j == i:
                term = kron(term, Z, format="csr")
            else:
                term = kron(term, I, format="csr")
        H += -h * term
    
    return H

def ising_dodecahedron(N, J):
    """
    Constructs the Hamiltonian for the transverse field Ising model on a dodecahedral molecular structure without transverse field.

    Parameters:
        N (int): Number of spins (should match the dodecahedral molecule, typically N=20).
        J (float): Interaction strength.
    
    Returns:
        H (scipy.sparse.csr_matrix): The Hamiltonian matrix in sparse format.
    """
    if N != 20:
        raise ValueError("Dodecahedral molecules typically have N = 20 sites.")

    # Sparse identity matrix
    I = identity(2, format="csr")
    
    # Pauli matrices as sparse matrices
    X = csr_matrix(pauli_x())
    
    # Initialize the Hamiltonian
    H = csr_matrix((2**N, 2**N), dtype=np.float64)

    # Get Dodecahedron bonds
    bonds = dodecahedral_bonds()

    # Interaction term: J * sigma_i^x * sigma_j^x for Dodecahedron connectivity
    for i, j in bonds:
        term = 1
        for k in range(N):
            if k == i or k == j:
                term = kron(term, X, format="csr")
            else:
                term = kron(term, I, format="csr")
        H += J * term
    
    return H

def transverse_field_dodecahedral(N, h):
    """
    Constructs the Hamiltonian for the transverse field Ising model on a dodecahedral molecular structure.

    Parameters:
        N (int): Number of spins (should match the icosahedral molecule, typically N=20).
        J (float): Interaction strength.
        h (float): Transverse field strength.
    
    Returns:
        H (scipy.sparse.csr_matrix): The Hamiltonian matrix in sparse format.
    """
    if N != 20:
        raise ValueError("Dodecahedral molecules typically have N = 20 sites.")

    # Sparse identity matrix
    I = identity(2, format="csr")
    
    # Pauli matrices as sparse matrices
    Z = csr_matrix(pauli_z())
    
    # Initialize the Hamiltonian
    H = csr_matrix((2**N, 2**N), dtype=np.float64)

    # Get dodecahedral bonds
    bonds = dodecahedral_bonds()

    # Transverse field term: -h * sigma_i^z
    for i in range(N):
        term = 1
        for j in range(N):
            if j == i:
                term = kron(term, Z, format="csr")
            else:
                term = kron(term, I, format="csr")
        H += -h * term
    
    return H

def H_shifted(H0, x):
    H_s = H0 - x * identity(H0.shape[0], format="csr")
    H_s = H_s.tocsr()
    return H_s


def H_shifted_sq(H0, x):
    H_s = H0 - x * identity(H0.shape[0], format="csr")
    H_s_sq = H_s @ H_s
    H_s_sq = H_s_sq.tocsr()
    return H_s_sq

def resid_norms(Aop, evals, evecs):
    # Works with either a matrix or LinearOperator
    R = Aop @ evecs - evecs * evals
    return np.linalg.norm(R, axis=0)

def combine_cols(V):
    # Make a v0 from current Ritz vectors (works even if we have just 1)
    c = np.random.randn(V.shape[1])
    c /= np.linalg.norm(c)
    v0 = V @ c
    v0 /= np.linalg.norm(v0)
    return v0

def probe_eigsh(
    A, k=6, which='LM',  # 'SA'/'LA' for extremal; with sigma use which='LM'
    maxiter_step=10, steps=10,
    ncv=None, tol=1e-10, v0=None,
    sigma=18.1, OPinv=None, mode='normal',
    verbose=True
):
    """
    Run eigsh in short bursts, printing residuals after each burst.
    Works with normal and shift-invert (set sigma and optionally OPinv).
    """
    last_v0 = v0
    converged_wV = None

    for s in range(1, steps+1):
        try:
            w, V = eigsh(A, k=k, which=which, ncv=ncv, tol=tol,
                         maxiter=maxiter_step, v0=last_v0,
                         sigma=sigma, OPinv=OPinv, mode=mode,
                         return_eigenvectors=True)
            if verbose:
                res = resid_norms(A if sigma is None else LinearOperator(A.shape, matvec=lambda x: A @ x), w, V)
                print(f"[step {s}] CONVERGED: k={k}  maxiter={maxiter_step}  "
                      f"residuals min/median/max = {res.min():.2e}/{np.median(res):.2e}/{res.max():.2e}", flush=True)
            converged_wV = (w, V)
            break
        except ArpackNoConvergence as err:
            w = err.eigenvalues
            V = err.eigenvectors
            if V is not None and V.size:
                res = resid_norms(A if sigma is None else LinearOperator(A.shape, matvec=lambda x: A @ x), w, V)
                if verbose:
                    print(f"[step {s}] PARTIAL: {V.shape[1]} Ritz vectors; "
                          f"residuals min/median/max = {res.min():.2e}/{np.median(res):.2e}/{res.max():.2e}", flush=True)
                last_v0 = combine_cols(V)  # warm-start next burst
                converged_wV = (w, V)
            else:
                if verbose:
                    print(f"[step {s}] NO RITZ VECTORS YET — try larger ncv or more steps.", flush=True)
                # random warm start to shake things up a bit
                n = A.shape[0]
                last_v0 = np.random.randn(n); last_v0 /= np.linalg.norm(last_v0)

    return converged_wV  # (w, V) from last attempt (maybe partial)



In [3]:
N = 20  # Number of spins
J = 1.0  # Interaction strength
h = 3.0  # Transverse field strength # this is the value in the paper. maybe try other values too, including the critical value one (h=J=1)


# Assuming transverse_field_ising is defined and returns a sparse Hermitian matrix
H = transverse_field_ising_dodecahedral(N, J, h)
Hi = ising_dodecahedron(N, J)
Htf = transverse_field_dodecahedral(N, h)

In [ ]:
eiv, eig = eigsh(H, k=5, sigma=-18.0, which='LM', maxiter=1, tol=1e-5)
#E0 = -18.0
#H_shifted = H - E0 * identity(H.shape[0], format="csr")
#H_sq = H_shifted @ H_shifted # with this which = 'SA' finds the smallest eigenvalue of H^2, which is (E0 - E)^2
#eivt, eigt = eigsh(H_shifted, k=5, which='SM', maxiter=500, ncv=128, tol=1e-5)
# The closest eigenvalue of H is: E0 ± sqrt(eivt[0])

In [7]:
def make_sq_jacobi_precond(B, eps=1e-10):
    # diag(B^2) without forming B@B
    row_ptrs, data = B.indptr, B.data
    n = B.shape[0]
    diag_B2 = np.empty(n)
    for i in range(n):
        s, e = row_ptrs[i], row_ptrs[i+1]
        # sum of squares along row i
        diag_B2[i] = np.dot(data[s:e], data[s:e])
    invd = 1.0 / (diag_B2 + eps)

    def mv(x):        # (n,) -> (n,)
        return invd * x
    def mm(X):        # (n,k) -> (n,k)
        return invd[:, None] * X

    return LinearOperator(B.shape, matvec=mv, rmatvec=mv, matmat=mm, rmatmat=mm)

E0 = -6.0
n = H.shape[0]
B = H - E0 * eye(n, format="csr")
M_sq = make_sq_jacobi_precond(B)

In [8]:

# A2 = (H - E0 I)^2 as a LinearOperator (no explicit square)
def A2_mv(x):          # (n,) -> (n,)
    return B @ (B @ x)

def A2_mm(X):          # (n,k) -> (n,k)
    return B @ (B @ X)

A2 = LinearOperator((n, n), matvec=A2_mv, rmatvec=A2_mv, matmat=A2_mm, rmatmat=A2_mm)

# Choose ONE preconditioner:
# M = M_shift
# M = M_sq
M = M_sq   # usually best among cheap options

# Block initial guesses (good for a 5-fold multiplet)
k = 5
X0 = np.random.randn(n, k)
# Orthonormalize cheaply; QR on (n,k) is fine but you can skip if X0 is random and k is small.
X0, _ = np.linalg.qr(X0, mode="reduced")

M = make_sq_jacobi_precond(B)

vals_mu, vecs = lobpcg(A2, X0, M=M, largest=False, tol=1e-8, maxiter=500)
E = np.array([(v @ (H @ v)) / (v @ v) for v in vecs.T])


C:\Users\camipolv\AppData\Local\Temp\ipykernel_24080\3772186743.py:23: UserWarning: Exited at iteration 500 with accuracies 
[0.04300348 0.04261873 0.04375654 0.04679266 0.04559938]
not reaching the requested tolerance 1e-08.
Use iteration 500 instead with accuracy 
0.044120997595863.

  vals_mu, vecs = lobpcg(A2, X0, M=M, largest=False, tol=1e-8, maxiter=500)
C:\Users\camipolv\AppData\Local\Temp\ipykernel_24080\3772186743.py:23: UserWarning: Exited postprocessing with accuracies 
[0.04236143 0.04241208 0.04352519 0.04642236 0.04588393]
not reaching the requested tolerance 1e-08.
  vals_mu, vecs = lobpcg(A2, X0, M=M, largest=False, tol=1e-8, maxiter=500)


In [6]:
print(vals_mu)

[0.00305455 0.00321696 0.00330866 0.00341605 0.00360906]
