In [1]:
import numpy as np
from functools import reduce
from scipy.linalg import eigh
import matplotlib.pyplot as plt
from scipy.sparse import kron, identity, csr_matrix, lil_matrix
from scipy.sparse.linalg import eigsh, eigs
from qutip import Qobj, ptrace
from qutip import commutator as qt_commutator
from tqdm import tqdm
from itertools import product

In [2]:
#debugging dense vs sparse matrices

dense_matrix = np.array([[1, 2, 0],
                         [0, 3, 4],
                         [5, 0, 6]])

print(f"dense matrix type + dim: {dense_matrix.dtype}, {dense_matrix.shape}")
print(f"dense matrix: {dense_matrix}")

# Diagonalize the dense matrix
eigenvalues, eigenvectors = np.linalg.eig(dense_matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


dense_to_sparse = csr_matrix(dense_matrix)
print(f"sparse matrix type + dim: {dense_to_sparse.dtype}, {dense_to_sparse.shape}")
print(f"dense to sparse: {dense_to_sparse}")

sparse_matrix = csr_matrix([[1, 2, 0],
                            [0, 3, 4],
                            [5, 0, 6]])

print(f"sparse matrix type + dim: {sparse_matrix.dtype}, {sparse_matrix.shape}")
print(f"sparse matrix: {sparse_matrix}")

# Diagonalize the sparse matrix - scipy uses Lanczos algorithm
# Note: eigs returns a limited number of eigenvalues and eigenvectors (default is 6)
# You can specify the number of eigenvalues/eigenvectors to compute with the 'k' parameter
#eigenvalues, eigenvectors = eigs(sparse_matrix, k=3) - this sparse matrix is too  small for eigs

#print("Eigenvalues:", eigenvalues)
#print("Eigenvectors:\n", eigenvectors)

sparse_to_dense = sparse_matrix.toarray()
print(f"dense matrix type + dim: {sparse_to_dense.dtype}, {sparse_to_dense.shape}")
print(f"sparse to dense: {sparse_to_dense}")

# Diagonalize the dense matrix
eigenvalues, eigenvectors = np.linalg.eig(sparse_to_dense)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

dense matrix type + dim: int32, (3, 3)
dense matrix: [[1 2 0]
 [0 3 4]
 [5 0 6]]
Eigenvalues: [7.41325908+0.j         1.29337046+2.48012343j 1.29337046-2.48012343j]
Eigenvectors:
 [[ 0.20498276+0.j         -0.06331188+0.5352321j  -0.06331188-0.5352321j ]
 [ 0.65730377+0.j         -0.67300775+0.j         -0.67300775-0.j        ]
 [ 0.72521295+0.j          0.28714373-0.41728557j  0.28714373+0.41728557j]]
sparse matrix type + dim: int32, (3, 3)
dense to sparse:   (0, 0)	1
  (0, 1)	2
  (1, 1)	3
  (1, 2)	4
  (2, 0)	5
  (2, 2)	6
sparse matrix type + dim: int32, (3, 3)
sparse matrix:   (0, 0)	1
  (0, 1)	2
  (1, 1)	3
  (1, 2)	4
  (2, 0)	5
  (2, 2)	6
dense matrix type + dim: int32, (3, 3)
sparse to dense: [[1 2 0]
 [0 3 4]
 [5 0 6]]
Eigenvalues: [7.41325908+0.j         1.29337046+2.48012343j 1.29337046-2.48012343j]
Eigenvectors:
 [[ 0.20498276+0.j         -0.06331188+0.5352321j  -0.06331188-0.5352321j ]
 [ 0.65730377+0.j         -0.67300775+0.j         -0.67300775-0.j        ]
 [ 0.72521295+0.j